spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/mertcantahanli/config-server-t2
server:
  port: 8888